Repository DFE-Digital/get-a-teacher-relocation-payment, pull requests merged in 2023-06, with the labels that each got.

#56 Add review apps
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-review-app.yml
  .gitignore
  Makefile
  config/environments/review.rb
  docs/aks-cheatsheet.md
  global_config/review.sh
  terraform/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/cluster_data.tf
  terraform/aks/config/app_config.yml
  terraform/aks/config/review.tfvars.json
  terraform/aks/config/review_Terrafile
  terraform/aks/data.tf
  terraform/aks/databases.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/variables.tf
Labels: deploy, DevOps

#60 Update subjects: remove general science
  app/models/applicants/subject.rb
Labels: deploy

#61 Add Azure DNS zone and records
  Makefile
  global_config/dns-domain.sh
  terraform/custom_domains/environment_domains/config/trp_qa.tfvars.json
  terraform/custom_domains/environment_domains/config/trp_qa_backend.tfvars
  terraform/custom_domains/environment_domains/main.tf
  terraform/custom_domains/environment_domains/monitoring.tf
  terraform/custom_domains/environment_domains/terraform.tf
  terraform/custom_domains/environment_domains/variables.tf
  terraform/custom_domains/infrastructure/config/trp.tfvars.json
  terraform/custom_domains/infrastructure/config/trp_backend.tfvars
  terraform/custom_domains/infrastructure/main.tf
  terraform/custom_domains/infrastructure/terraform.tf
  terraform/custom_domains/infrastructure/variables.tf
Labels: DevOps

#84 Fix aks app module kv name after module change
  terraform/aks/application.tf
Labels: deploy, DevOps

#86 Add a new dashboard page with a KPI widget
  .github/workflows/ci.yml
  .rubocop.yml
  app/controllers/system_admin/dashboard_controller.rb
  app/javascript/packs/stylesheets/custom.scss
  app/javascript/packs/stylesheets/govuk.scss
  app/models/kpis.rb
  app/views/system_admin/dashboard/show.html.erb
  config/routes.rb
  spec/features/admin_console/dashboard_spec.rb
  spec/models/kpis_spec.rb
  spec/spec_helper.rb
  spec/support/admin_helpers.rb
Labels: deploy

#102 Create qa environment
  .github/workflows/build-and-deploy.yml
  Makefile
  config/environments/qa.rb
  global_config/qa.sh
  terraform/aks/config/app_config.yml
  terraform/aks/config/qa.tfvars.json
  terraform/aks/config/qa_Terrafile
  terraform/aks/databases.tf
  terraform/aks/variables.tf
  terraform/custom_domains/environment_domains/config/trp_qa.tfvars.json
Labels: DevOps
