Repository DFE-Digital/get-a-teacher-relocation-payment, pull requests merged in 2023-07, with the labels that each got.

#113 Create staging environment
  .github/workflows/build-and-deploy.yml
  Makefile
  config/environments/staging.rb
  global_config/staging.sh
  terraform/aks/config/app_config.yml
  terraform/aks/config/staging.tfvars.json
  terraform/aks/config/staging_Terrafile
  terraform/aks/variables.tf
  terraform/custom_domains/environment_domains/config/trp_staging.tfvars.json
  terraform/custom_domains/environment_domains/config/trp_staging_backend.tfvars
Labels: deploy, DevOps

#148 Create production environment
  .github/workflows/build-and-deploy.yml
  Makefile
  global_config/production.sh
  terraform/aks/config/app_config.yml
  terraform/aks/config/production.tfvars.json
  terraform/aks/config/production_Terrafile
  terraform/custom_domains/environment_domains/config/trp_production.tfvars.json
  terraform/custom_domains/environment_domains/config/trp_production_backend.tfvars
Labels: DevOps

#141 Breadcrumbs
  app/views/layouts/admin.html.erb
  app/views/system_admin/applicants/edit.html.erb
  app/views/system_admin/applicants/show.html.erb
Labels: deploy

#140 Adding searching capabilities
  app/controllers/system_admin/applicants_controller.rb
  app/models/application.rb
  app/views/system_admin/applicants/index.html.erb
  spec/features/admin_console/applications_list_spec.rb
  spec/models/application_spec.rb
Labels: deploy

#149 Filter by Status
  .rubocop.yml
  app/controllers/system_admin/applicants_controller.rb
  app/models/application.rb
  app/models/application_progress.rb
  app/queries/status_query.rb
  app/views/system_admin/applicants/index.html.erb
  db/migrate/20230710073505_add_status_to_application_progresses.rb
  db/schema.rb
  spec/factories/application_progresses.rb
  spec/features/admin_console/applications_list_spec.rb
  spec/models/application_progress_spec.rb
  spec/models/application_spec.rb
  spec/queries/status_query_spec.rb
Labels: deploy
