Repository DFE-Digital/get-a-teacher-relocation-payment, pull requests merged in 2024-06, with the labels that each got.

#422 Configure semantic logger
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/semantic_logger.rb
Labels: deploy

#424 Service Onboard to Logit.io
  terraform/aks/application.tf
  terraform/aks/config/qa.tfvars.json
  terraform/aks/config/review.tfvars.json
  terraform/aks/config/staging.tfvars.json
  terraform/aks/variables.tf
Labels: deploy

#425 Update azurerm provider
  .github/actions/deploy/action.yml
  terraform/aks/terraform.tf
  terraform/custom_domains/environment_domains/terraform.tf
  terraform/custom_domains/infrastructure/terraform.tf
Labels: deploy, DevOps

#430 Upgrade rails 7.1.3.3 => 7.1.3.4
  Gemfile.lock
Labels: deploy

#429 logitio changes reverted
  terraform/aks/application.tf
  terraform/aks/config/qa.tfvars.json
  terraform/aks/config/review.tfvars.json
  terraform/aks/config/staging.tfvars.json
  terraform/aks/variables.tf
Labels: DevOps
